### ISSUE TITLE
Improve Receipt indexing and lookup performance in Lotus

### ISSUE THREAD

**Issue by i-norden** [vulcanize/filecoin-indexing#19]
Background:

Lotus maintains sqlite indexes for fast transaction lookup: https://github.com/filecoin-project/lotus/blob/master/chain/index/msgindex.go

We can see this index being leveraged in the `SearchForMessages` method: https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L140

In `SearchForMessages` we first load the message directly from the blockstore using the provided CID: https://github.com/filecoin-project/lotus/blob/master/chain/store/messages.go#L43.

Once we have the message, we attempt to find the corresponding receipt in the `head-1` ("head" being the tipset provided to the method) tipset by calling [tipsetExecutedMessage](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L146). This method [loads the parent-of-head tipset](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L307), [loads the messages for the parent tipset](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L312), scans backwards through these messages (in order to account for [replaceable](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L331) message CIDs). Once it has identified the correct (potentially replaced) message through this process, it takes the index of that message and uses it to [lookup the corresponding receipt](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L339). The receipt lookup itself involves [loading and searching through the AMT for the receipts](https://github.com/filecoin-project/lotus/blob/master/chain/store/messages.go#L314).

If we couldn't find the receipt in the `head-1` tipset using the above process, then we attempt to lookup `msgInfo` in the [sqlite message index](https://github.com/filecoin-project/lotus/blob/master/chain/index/msgindex.go) by calling [searchForIndexedMsg](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L192). This method searches the index for the messageCID and the index maps this CID to the appropriate tipset to lookup the receipts with. We then call the [tipsetExecutedMessage](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L223) method again, this time using the tipset that we identified from the index.

If `msgInfo` cannot be found in the index, then we fall through to the most pessimistic search path which involves calling the [searchBackForMsg](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L178). As the name implies, this method involves iterating backwards over tipsets from the provided head, searching through all the messages until the target message and corresponding receipt are found (or until the search limit is reached).

Ideas (WIP):

1. We need a secondary index for receipts. The sqlite message index maps messageCIDs to tipset keys, but we still have to then load the TipSet and then search through its referenced receipt AMT to retrieve the corresponding receipt. We could instead index the corresponding receipt CID directly in the sqlite table, or do something similar to geth where we maintain a KVStore bucket that allows us to prepend a simple prefix (e.g. `[]byte("r")`) to a message CID to directly lookup the corresponding receipt or receipt CID. 
2. Better guarantees that the sqlite index will actually be hit, preventing us from having to go down the expensive `searchBackForMsg` path.
3. The search path is made to accommodate `allowReplaced`. Even when `allowReplaced` is false, the access pattern proceeds down a non-optimal path in order to accommodate the possibility for it to be true. If we know it can't be replaced, then we should be able to avoid some of the work done in [tipsetExecutedMessage](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/searchwait.go#L301). Need to investigate this further.

**Comment by i-norden** [comment]
This path is taken when servicing `eth_getTransactionReceipt` requests

`eth_getTransactionReceipt` is ultimately an alias/shim on-top of this method: https://github.com/filecoin-project/lotus/blob/master/node/impl/full/eth.go#L427 which calls `StateSearchMsg`.

**Comment by fridrik01** [comment]
> I think there is a “quick” fix to slow `eth_getTransactionReceipt` queries that are looking for old receipts. The biggest issue when looking for a super early receipt is that when the endpoint is called the `StateSearchMsg` method described above is called with a `types.EmptyTSK`
> 
> This means the `StateSearchMsg` defaults to using the heaviest tipsetkey, which is super far away from any early/earliest message/receipt. So if the message CID is not found in the message index, we fall down to the worst path and end up iterating over every single tipset back from head until we find the target receipt.
> 
> If we somehow maintained a mapping of tx_hashes/msg_CIDs to epoch/tipsetkey and were able to pass in the correct tipset or one much closer to the target one I think that would speed things up dramatically without having to change any of the internals of `StateSearchMsg`.
> 
> We can test this hypothesis quickly by hardcoding passing in the correct or a much closer tipsetkey to `StateSearchMsg` when `eth_getTransactionReceipt` is called.

We definitely need to have better guarantees that the relevant sql indices are properly maintained. For example, the logic for backfilling the sqlite index relevant to `eth_getTransactionReceipt` needs to be reconsidered IMO as it simply skips backfilling if the `sqlite/txhash.db` already exists ([see relevant code](https://github.com/filecoin-project/lotus/blob/master/node/modules/ethmodule.go#L51)). Could this be what is happening in your case?

**Comment by i-norden** [comment]
Clear the `sqlite/` directories before running node ontop of fresh snapshot.

**Comment by i-norden** [comment]
A message can be in the local blockstore but not in the chain, so we can't simply revert to maintenance mode when we can fidn a message in blockstore but not in the messages index.

We can rely on federation with other nodes to check if message needs to be in index?

DO THE BELOW:

Hashing/snapshotting/checkpointing the database periodically so that we can check if it is correct/complete? Create a new empty db, attach to current db, pop regions that predefined for hashing over into the new DB, hash the new DB, should get the same hash. Need some way to store and expose these checkpoints, canonical hash tree? Would this be a sidecar process or part of Lotus? Eventually add Lotus API to support this?

Map epoch boundaries to the canonical hash. Need to define an attestation schema. ETL sql statement to take msgindex and populate the new schema. Run hash over these segments. 

Service runs alongside Lotus and performs this algo, checks the hashes it generates vs the ones exposed by other SPs. If it is not a canonical hash, stop the node, fix the index, restart it, re-run test. Service needs to run this algo every "period". 

"period": 2880 epochs (1 day)

See https://github.com/ribasushi/fil-fip36-vote-tally/blob/master/parsestate/model.go#L39-L68

Trailing process that probes the index in the background and checks that the messages it contains are sufficient to satisfy state transitions?

**Comment by jennijuju** [comment]
Did you enable https://github.com/filecoin-project/lotus/blob/41203f7b8e602124aea4d2f9c23d18bee8f8e68e/node/config/types.go#L738-L740??

**Comment by jennijuju** [comment]
if you already have the state but not the index `lotus-shed msgindex backfill` can help you backfill them

**Comment by i-norden** [comment]
While syncing from the light snapshots, we have noticed at startup that the node's struggle to find peers. It eventually does, but then it continues to run into these issues with a high frequency: 

```
ID": "f01146045"}
2023-06-12T17:35:20.871Z        WARN    sub     sub/incoming.go:544     cannot authenticate messsage    {"err": "failed to load miner actor: actor not found", "errVerbose": "failed to load miner actor:\n    github.com/filecoin-project/lotus/node/impl/full.(*StateModule).StateMinerInfo\n        /home/srw/lotus/node/impl/full/state.go:153\n  - actor not found", "peer": "12D3KooWBjsDHppZZqumacEmJqfuUSBd6x41aCeVCdo1gcM11iyA", "minerID": "f02182902"}
2023-06-12T17:35:21.251Z        WARN    sub     sub/incoming.go:544     cannot authenticate messsage    {"err": "failed to load miner actor: actor not found", "errVerbose": "failed to load miner actor:\n    github.com/filecoin-project/lotus/node/impl/full.(*StateModule).StateMinerInfo\n        /home/srw/lotus/node/impl/full/state.go:153\n  - actor not found", "peer": "12D3KooWEiPRcfjXJVehty8okJGJpBZP8zM5UBoCK5yw2MXfx98x", "minerID": "f02098126"}
```

and 

```
2023-06-12T17:36:23.749Z        INFO    net/identify    identify/id.go:432      failed negotiate identify protocol with peer    {"peer": "12D3KooWFvcNjT29GtPwaT6VeMGMoAJZXJ4GRZ9JkUpQ73b2aodn", "error": "stream reset"}
2023-06-12T17:36:23.750Z        WARN    net/identify    identify/id.go:407      failed to identify 12D3KooWFvcNjT29GtPwaT6VeMGMoAJZXJ4GRZ9JkUpQ73b2aodn: stream reset
2023-06-12T17:36:24.731Z        INFO    consensus-common        consensus/compute_state.go:301  ApplyBlocks stats       {"early": 0.00000782, "earlyCronGas": 0, "vmMsg": 2.996465943, "msgGas": 26812048661, "vmCron": 10.457947094, "cronGas": 450624768184, "vmFlush": 1.945487151, "epoch": "2757064", "tsk": "{bafy2bzacedngohola2r3qrekkyitohqucrwaemu72lcavhzncmsj4atvpgbdu,bafy2bzacecslqgxoqyquarokju72zfozbhvlvjwxhazsewg3hc4yjukfkxzg6,bafy2bzaceb5ecnsbbfhki66mhqjprt2uz3xniqxythv6jfhnqwaeh5bjc73m2,bafy2bzacedhc5ysif3fhvyqf7fmrkbqdasf35cfnttui66bjwgvp5n3btjiz6,bafy2bzacebr4wuxolzmonyp377iluvnt24gy7i4re5emw6u5ht3mb7msesjei,bafy2bzacedodefp32o5mjhd35k5zeebzf2rwuzohnuy6tutlchohywua465ly,bafy2bzacec34bzudacjs2olicf6qwp3qoaysppi6mebqykaj2ztu5bngrg4c2}"}
```

**Comment by jennijuju** [comment]
> If you are aware of anybody who could provide a full snapshot or transfer the data dir for a non-pruning node synced from a light snapshot below 2683348 we would be very interested in that.

There is one potential provider AFAIK & they are doing some testing. @eshon might have more updated info to share here.

**Comment by jennijuju** [comment]
>  These syncs were (re)started about 2 weeks ago but have not yet completed (around epoch 2750000 now; at current rate will take 5-6 more weeks)

Small good news i hope:  i expect the sync to be faster passing epoch 2809800 due to a protocol improvement we shipped to the network!

**Comment by i-norden** [comment]
Thanks @jennijuju, we successfully transferred an archive node. Between what you shared here and the recent work that has been done on the skip list and otherwise by @fridrik01 I'm closing this. Thanks!!
