### ISSUE TITLE
Improve `eth_getBlockByNumber` query performance.

### ISSUE THREAD

**Issue by i-norden** [vulcanize/filecoin-indexing#20]
This API endpoint is a wrapper around the [EthModule.EthGetBlockByNumber](https://github.com/filecoin-project/lotus/blob/master/node/impl/full/eth.go#L279) method. This method calls [parseBlkParam](https://github.com/filecoin-project/lotus/blob/master/node/impl/full/eth.go#L244) which is where I believe the problem occurs. When we pass in a blocknumber, that methods falls through to [this](https://github.com/filecoin-project/lotus/blob/master/node/impl/full/eth.go#L259) switch statement, which calls [ChainGetTipSetByHeight](https://github.com/filecoin-project/lotus/blob/master/node/impl/full/eth.go#L268) which calls [GetTipsetByHeight](https://github.com/filecoin-project/lotus/blob/master/node/impl/full/chain.go#L241). Importantly, it appears that no matter how far back we are looking for a tipset it passes the `head` (heaviest) tipset to these methods as the starting point for a backwards walk. Inside the `GetTipsetByHeight` method we call ["ChainIndex".GetTipSetByHeight](https://github.com/filecoin-project/lotus/blob/master/chain/store/index.go#L61), but this method doesn't appear to actually use an `epoch => tipset` index, rather it is a hot cache wrapped around a very slow iterative search backwards through every tipset starting from the `head` until we find the tipset with the desired epoch: https://github.com/filecoin-project/lotus/blob/master/chain/store/index.go#L103.

**Comment by i-norden** [comment]
At a high level I think we can boil down there issues for this and #19 to three missing indexes:

`height => tipsetkey`
`tx_cid => tipsetkey`
`tx_cid => receipt_cid`

**Comment by fridrik01** [comment]
The skiplist implementation introduced in [this PR](https://github.com/filecoin-project/lotus/pull/10423) improved the `ChainIndex.GetTipsetByHeight` method to be "1000x faster". However, I think its slow the first time since it needs to hot-load the cache (which is not ideal).

But, with this skiplist all in cache, does that address this `eth_getBlockByNumber` query performance, or is it still a problem?

**Comment by i-norden** [comment]
Thanks @fridrik01, warming up the cache did work (once we were running the right version of lotus 🙃). We are going to test the PR that warms-up on node standup too, haven't done that yet. 

I still think using the msgindex.db table to go from epoch=>tipsetkey could bypass needing the cache entirely and that that would be preferable in cases where we already have msgindex.db enabled. 

Also running into some general syncing issues, described in greater detail [here](https://github.com/vulcanize/filecoin-indexing/issues/19#issuecomment-1587778977) which are limiting us from testing historical msg and receipt stuff.
